# Generated by Django 3.1.4 on 2020-12-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='description',
            field=models.TextField(),
        ),
    ]
