# Generated by Django 3.1.4 on 2020-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin', '0008_auto_20201214_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='command',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
